renv documentation added
The-Strategy-Unit/data_science pull request #242
Opened 2024-11-11 18:12 UTC by yiwen-h

Closes #239 
Does it make sense??

2024-11-11 18:19 UTC, tomjemmett requested changes
I think there are some more specific points to make, but on phone currently. Will update properly later!

2024-11-15 13:58 UTC, tomjemmett requested changes
see comments

2024-11-15 13:58 UTC, tomjemmett commented on README.md
> +2. If your presentation requires any specific packages, capture them with `renv::snapshot("PATH_TO_THE_FOLDER")` and ensure that you include in the top of your .qmd file (after the yaml) the followin
for now, I think we need to always snapshot - need to investigate this more thoroughly (as R shouldn't be a dependency for this)

2024-11-15 13:58 UTC, tomjemmett commented on README.md
> +5. If your blogpost requires any specific packages, capture them with `renv::snapshot("PATH_TO_THE_FOLDER")` and ensure that you include in the top of your .qmd file (after the yaml) the following co
as above

2024-11-18 12:41 UTC, tomjemmett approved these changes

2024-11-18 13:56 UTC, ChrisBeeley approved these changes
I think the PR is great. I think I have some longer questions about whether relative novices are capable of contributing to this repo, but this is a great start to having better documentation

2024-11-18 15:58 UTC, merged