Sheila's blog - Mapping my journey in R
The-Strategy-Unit/data_science pull request #266
Opened 2024-12-20 15:48 UTC by sheilamomo

Blog post - following up from and summarizing Sheila's coffee and coding session in June. Closes #162.

2024-12-20 16:49 UTC, sheilamomo commented
Sorry - spotted that I need to go back and make some revisions to the draft blog post. Will update when ready

2024-12-23 16:41 UTC, StatsRhian commented
No worries - I've removed myself as reviewer whilst it's in draft. Can you add me again when you're ready please :) 
Look forward to reading!

2025-03-10 18:12 UTC, ChrisBeeley requested changes
Love it!

As another step on your GitHub learning journey I've made a suggestion in my review. It's very simple to accept the change as detailed here

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/incorporating-feedback-in-your-pull-request#applying-suggested-changes

My changes will add in a date and you as author. If you need any help with this part of the review process just give me a shout and I can help

2025-03-11 09:35 UTC, sheilamomo commented on blogs/posts/2024-11-29-mapping-my-r-learning/index.qmd
> +editor: visual
Sounds good, thanks!

2025-03-11 09:39 UTC, ChrisBeeley approved these changes

2025-03-11 09:39 UTC, merged