adds a blog post for reinstalling r packages after updating r
The-Strategy-Unit/data_science pull request #33
Opened 2023-04-26 10:26 UTC by tomjemmett

2023-04-26 11:37 UTC, Lextuga007 commented on blogs/posts/2023-04-26-reinstalling-r-packages.qmd
> +If you look at the script I first install a number of packages from CRAN, then I install packages that only exist on GitHub.
I've updated today and realised that it goes to another folder so I still have access to 4.2.2 through Tools/Global Options and change the R version. It means I still have access to all or my old installed packages even though I forgot to look what I should note down to follow this!

2023-04-26 11:39 UTC, Lextuga007 requested changes

2023-04-26 11:39 UTC, Lextuga007 commented on blogs/posts/2023-04-26-reinstalling-r-packages.qmd
> +to run the script. Generally, sourcing a url is a bad idea - the reason for this is if it's not a link that you control, then someone could update the contents and run arbritary code on your machine.
Bit of a repetition as you wrote "simply run" before the url and then "to run the script" at the end.

Nice warning though!

2023-04-26 13:03 UTC, Lextuga007 approved these changes

2023-04-26 13:04 UTC, merged

2024-05-20 10:23 UTC, tomjemmett commented
@all-contributors
please add @tomjemmett for blog